package com.dodo.project.rebate.rebot.dao.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemMenuNode<M extends BaseSystemMenuNode<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menu_id");
	}

	public void setIsMenu(java.lang.Boolean isMenu) {
		set("is_menu", isMenu);
	}
	
	public java.lang.Boolean getIsMenu() {
		return get("is_menu");
	}

	public void setIsAuth(java.lang.Boolean isAuth) {
		set("is_auth", isAuth);
	}
	
	public java.lang.Boolean getIsAuth() {
		return get("is_auth");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
