package com.dodo.project.rebate.rebot.dao.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemUserNotify<M extends BaseSystemUserNotify<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setIsRead(java.lang.Boolean isRead) {
		set("is_read", isRead);
	}
	
	public java.lang.Boolean getIsRead() {
		return get("is_read");
	}

	public void setSystemUserId(java.lang.Integer systemUserId) {
		set("system_user_id", systemUserId);
	}
	
	public java.lang.Integer getSystemUserId() {
		return getInt("system_user_id");
	}

	public void setNotifyId(java.lang.Integer notifyId) {
		set("notify_id", notifyId);
	}
	
	public java.lang.Integer getNotifyId() {
		return getInt("notify_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
