package com.dodo.project.rebate.rebot.dao.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemConfig<M extends BaseSystemConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}
	
	public java.lang.String getAppName() {
		return getStr("app_name");
	}

	public void setAppVersion(java.lang.String appVersion) {
		set("app_version", appVersion);
	}
	
	public java.lang.String getAppVersion() {
		return getStr("app_version");
	}

	public void setSiteName(java.lang.String siteName) {
		set("site_name", siteName);
	}
	
	public java.lang.String getSiteName() {
		return getStr("site_name");
	}

	public void setCopyRight(java.lang.String copyRight) {
		set("copy_right", copyRight);
	}
	
	public java.lang.String getCopyRight() {
		return getStr("copy_right");
	}

	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}
	
	public java.lang.String getBrowser() {
		return getStr("browser");
	}

	public void setMiitbeian(java.lang.String miitbeian) {
		set("miitbeian", miitbeian);
	}
	
	public java.lang.String getMiitbeian() {
		return getStr("miitbeian");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
