package com.dodo.project.rebate.rebot.dao.system.model;

import com.dodo.project.rebate.rebot.dao.system.model.base.BaseSystemUserGroupDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemUserGroupDetail extends BaseSystemUserGroupDetail<SystemUserGroupDetail> {
	public static final SystemUserGroupDetail dao = new SystemUserGroupDetail().dao();
}
