package com.dodo.project.rebate.rebot.dao.system.model;

import com.dodo.project.rebate.rebot.dao.system.model.base.BaseSystemNotify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemNotify extends BaseSystemNotify<SystemNotify> {
	public static final SystemNotify dao = new SystemNotify().dao();
}
