package com.dodo.project.rebate.rebot.dao.system.model;

import com.dodo.project.rebate.rebot.dao.system.model.base.BaseSystemUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemUser extends BaseSystemUser<SystemUser> {
	public static final SystemUser dao = new SystemUser().dao();
}
