package com.dodo.project.rebate.rebot.dao.system.model;

import com.dodo.project.rebate.rebot.dao.system.model.base.BaseSystemMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemMenu extends BaseSystemMenu<SystemMenu> {
	public static final SystemMenu dao = new SystemMenu().dao();
}
