package com.dodo.project.rebate.rebot.dao.system.model;

import com.dodo.project.rebate.rebot.dao.system.model.base.BaseSystemUserGroupRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemUserGroupRole extends BaseSystemUserGroupRole<SystemUserGroupRole> {
	public static final SystemUserGroupRole dao = new SystemUserGroupRole().dao();
}
