package com.dodo.project.rebate.rebot.dao.system.model;

import com.dodo.project.rebate.rebot.dao.system.model.base.BaseSystemRoleMenuMapping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemRoleMenuMapping extends BaseSystemRoleMenuMapping<SystemRoleMenuMapping> {
	public static final SystemRoleMenuMapping dao = new SystemRoleMenuMapping().dao();
}
