package com.dodo.project.rebate.rebot.dao.system.model;

import com.dodo.project.rebate.rebot.dao.system.model.base.BaseSystemUserGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemUserGroup extends BaseSystemUserGroup<SystemUserGroup> {
	public static final SystemUserGroup dao = new SystemUserGroup().dao();
}
