package com.dodo.project.rebate.rebot.dao.system.model;

import com.dodo.project.rebate.rebot.dao.system.model.base.BaseSystemSubscription;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemSubscription extends BaseSystemSubscription<SystemSubscription> {
	public static final SystemSubscription dao = new SystemSubscription().dao();
}
